apiVersion: apps/v1
kind: Deployment
metadata:
  name: fit-deployment
  namespace: suwetha-ns
  labels:
    app: fit-app
spec:
  replicas: 8
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector: 
    matchLabels:
      app: fit
  template:
    metadata:
      labels:
        app: fit
    spec:
      containers:
        - name: fit-conatiner
          image: muralisocial123/fitness-app:v1.0.1
          ports:
            - containerPort: 3000
---
apiVersion: v1 
kind: Service
metadata:
  name: fit-deployment-svc
  namespace: suwetha-ns
spec: 
  selector:
    app: fit
    ports:
      - port: 3001 # It is service post number we are using to expose the applicatioon to the internet
        targetPort: 3000
        protocol: TCP 
    type: ClusterIP
